name: go-39

on:
  push
  
env:
  PUBLIC_REGISTRY_HOST: docker.io
  PUBLIC_REGISTRY_OWNER: nrsimkha
  PUBLIC_REGISTRY_APP_NAME: module-39

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.15.x'
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o $PUBLIC_REGISTRY_APP_NAME

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ github.workspace }}
      - run: go test -v ${{ github.workspace }}

  lint:
    if: always()
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.15.x'
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
      - run: golangci-lint --version
      - run: golangci-lint run
  
  image:
    container: ubuntu:latest
    runs-on: ubuntu-latest
    needs: [build,test,lint]
    if: github.ref == 'refs/heads/master'
    services:
      docker:
        image: docker:dind
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io          

      - name: Test Docker
        run: |
          docker version
          docker info
      - name: test secrets
        run: echo $PUBLIC_REGISTRY_OWNER
      -
        name: Login to Docker Huba
        uses: docker/login-action@v3
        env: # Or as an environment variable
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          username: $PUBLIC_REGISTRY_OWNER
          password: $dockerhub_token
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: user/app:latest     




