name: go-39-metoddostavkipril

on:
  push
  
env:
  PUBLIC_REGISTRY_HOST: docker.io
  PUBLIC_REGISTRY_OWNER: nrsimkha
  PUBLIC_REGISTRY_APP_NAME: module-39

jobs:
  build:
    runs-on: golang:latest
    steps:
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./${PUBLIC_REGISTRY_APP_NAME} ./

  test:
    runs-on: golang:latest
    needs: [build]
    steps:
      - run: echo "No tests!"

  lint:
    if: always()
    runs-on: golang:latest
    needs: [build]
    steps:
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
      - run: golangci-lint --version
      - run: golangci-lint run
  
  image:
    container: docker:latest
    runs-on: golang:latest
    needs: [build,test,lint]
    if: github.ref == 'refs/heads/master'
    services:
      docker:
        image: docker:dind
    steps:
      - run: echo "No build image commands!!!"     
      



